# Generated by `loom-bank build` — do not edit.
#
# GDScript integers are *signed* 64-bit and a literal >= 2^63 is a
# parse error, so ids are emitted as signed decimals with the
# unsigned hex alongside. Never print these as unsigned.
class_name LoomIDs

const PROGRAM_OPENING := -503093846918749417  # 0xf904a6cfcdb92317 opening
const PROGRAM_WAREHOUSE_ROW := 3114695110877076383  # 0x2b399eb373795b9f warehouse_row
const PROGRAM_CONFRONTED := 7133808825178580347  # 0x630061547850e57b confronted
const ENTITY_MARLOW := 1423599548027436267  # 0x13c1a43f1294fceb Marlow
const ENTITY_HARBOR := -180376050972110869  # 0xfd7f2ceff3d1cfeb Harbor
const ENTITY_WAREHOUSE := 5028594234458520996  # 0x45c927d0487a3da4 Warehouse
