#!/usr/bin/env node
// Seals the invite payload behind the puzzle passphrase and writes
// src/sealed.ts. The plaintext never ships in the bundle — the MEMBERS
// ONLY box derives the AES key from whatever the visitor types, so the
// only way in (short of brute force) is solving the cipher.
//
//   node scripts/seal.mjs DIALTONE payload.json
//
// Also prints the Vigenère ciphertext for the guestbook, so the two
// halves of the puzzle can never drift apart: edit PLAINTEXT/KEY here,
// re-run, and paste the printed groups into App.tsx if they changed.
import { webcrypto as crypto } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// ——— the Vigenère half (the visible puzzle) ———
// The decrypted instruction must name the passphrase used below.
const VIGENERE_PLAINTEXT = "THE MEMBERS DOOR OPENS TO THE WORD DIALTONE";
const VIGENERE_KEY = "MODEM"; // the ♥-list acrostic

function vigenere(text, key, decrypt = false) {
  const letters = text.toUpperCase().replace(/[^A-Z]/g, "");
  let out = "";
  for (let i = 0; i < letters.length; i++) {
    const p = letters.charCodeAt(i) - 65;
    const k = key.toUpperCase().charCodeAt(i % key.length) - 65;
    out += String.fromCharCode(65 + (decrypt ? (p - k + 26) % 26 : (p + k) % 26));
  }
  return out;
}

// ——— the AES half (the sealed door) ———
const [pass, payloadPath] = process.argv.slice(2);
if (!pass || !payloadPath) {
  console.error("usage: node scripts/seal.mjs <PASSPHRASE> <payload.json>");
  process.exit(1);
}
const norm = pass.toUpperCase().replace(/[^A-Z0-9]/g, "");
const payload = JSON.stringify(JSON.parse(readFileSync(payloadPath, "utf8")));

const salt = crypto.getRandomValues(new Uint8Array(16));
const iv = crypto.getRandomValues(new Uint8Array(12));
const keyMat = await crypto.subtle.importKey(
  "raw", new TextEncoder().encode(norm), "PBKDF2", false, ["deriveKey"],
);
const key = await crypto.subtle.deriveKey(
  { name: "PBKDF2", salt, iterations: 250_000, hash: "SHA-256" },
  keyMat, { name: "AES-GCM", length: 256 }, false, ["encrypt"],
);
const sealed = new Uint8Array(
  await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, new TextEncoder().encode(payload)),
);

const b64 = (u8) => Buffer.from(u8).toString("base64");
const out = `// Generated by scripts/seal.mjs — do not edit by hand.
// The invite payload, AES-GCM-sealed behind the puzzle passphrase.
export const SALT_B64 = "${b64(salt)}";
export const IV_B64 = "${b64(iv)}";
export const SEALED_B64 = "${b64(sealed)}";
`;
const dest = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "sealed.ts");
writeFileSync(dest, out);

const cipher = vigenere(VIGENERE_PLAINTEXT, VIGENERE_KEY);
const grouped = cipher.match(/.{1,5}/g).join(" ");
const check = vigenere(cipher, VIGENERE_KEY, true);
console.log("wrote", dest);
console.log("vigenère key       :", VIGENERE_KEY);
console.log("vigenère plaintext :", VIGENERE_PLAINTEXT);
console.log("guestbook cipher   :", grouped);
console.log("decrypt check      :", check);
if (!VIGENERE_PLAINTEXT.toUpperCase().replace(/[^A-Z]/g, "").includes(norm)) {
  console.warn("WARNING: the sealed passphrase does not appear in the Vigenère plaintext — the puzzle would be unsolvable!");
}
