// Generated by scripts/seal.mjs — do not edit by hand.
// The invite payload, AES-GCM-sealed behind the puzzle passphrase.
export const SALT_B64 = "5J9gZIfrnFO3VujFP7ep4w==";
export const IV_B64 = "SvdM8HGEImJ0mOq1";
export const SEALED_B64 = "upkzKKulE6+eFgGlBHwNx4Z80j/MtWxMG97dvzxi7zuyrtvv4wwjX4Or6gjMpOMYJdoivcc5giKyzC99BkbqmGv2Hw/YzCdZMXycYRROO09u/cm8XqCzZ5GAtVH5mbi+AENM7q7NWsCK+kpyKZ3+PwQEz/Tir6cPu+Qat2fkuzPO+oWedQFFAv4Lmjicc3X099JxE43e+d9gKMK+PkwksTwPD/vXvb/GhPtaZSn70/h4TAgenY02t2p/9FyXGy8nqJQP0aB6hI62fcCr1GkIMx0PFulsnr+4WN1cCW07PYs/5T1IYBd+4m7ziA9yZgd0UCmZbvoyci6/Y5/a2FUBpX/g";
