// Generated by scripts/seal.mjs — do not edit by hand.
// The invite payload, AES-GCM-sealed behind the puzzle passphrase.
export const SALT_B64 = "JDt7+D2sGHejxw0Jj/BqvA==";
export const IV_B64 = "AFKg4ebkSUUVdRdp";
export const SEALED_B64 = "wIkJr6sYHdX75SzA3ZDekXXea3wgMdxZ+JwX1lCPHv0TNXOyQB2BUol9HrRuaNp6hSJg8+/jyMxhlNswwkOjkhBWJIZjOkbp5St5WL8VgZf0ySiyNRhtnjBGmtHWCH1NvO4hLEpWYZVShA6fykWeVZNvuGDntFNFL9e7P8yxlixOZ0FIzJjlo8JUUAN4zY42H3OAI6iEssM11LkHD+87i3rTSoVIc/Nlps/l/z9S/NpkiUisYrzm0Ei2A4UkFNF/21xuN/0RwyNROx5yxg2HEKQKLsHd3HmJ/l4KBGIZlF9Uyg==";
