import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // `src/loom-wasm/` is wasm-pack output regenerated by
  // `pnpm wasm:build` — it ships with its own `eslint-disable` banner
  // and `tslint:disable` directives. Lint it elsewhere (Rust source).
  globalIgnores(['dist', 'src/loom-wasm']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      // Allow the conventional `_`-prefix to mark a destructured / function
      // argument we know is unused — primarily for the
      // `const { [path]: _gone, ...rest } = obj` pattern that drops a
      // property by rest-spread.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // The cockpit is ONE surface over two backends. Components read it
      // through `useCockpit` (resolved by `RunCockpit`); reaching for a
      // concrete store re-creates the Sim/Live fork this rule exists to
      // prevent. The allowlist below is the seam.
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: '@/store/operate', message: 'Read the cockpit through useCockpit; only the provider / resolver / App may import the server-run store.' },
            { name: '@/store/sim', message: 'Read the cockpit through useCockpit; only the provider / resolver / App may import the local-run store.' },
          ],
        },
      ],
    },
  },
  {
    files: [
      'src/components/cockpit/providers.tsx',
      'src/store/run.ts',
      'src/App.tsx',
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
    ],
    rules: { 'no-restricted-imports': 'off' },
  },
])
