//! Per-engine ID header codegen.
//!
//! One pass over the bank's name table drives all three languages, so
//! game code names a beat or signal symbolically and a rename breaks the
//! build instead of failing silently at runtime — the Wwise_IDs.h idea.

import { asSignedDecimal, fnv1a64 } from "./ids.ts";
import type { Bank } from "./ir.ts";

interface Symbol {
  ident: string;
  name: string;
  hash: bigint;
}

/** Upper-snake, kind-prefixed, with `_2` disambiguation on a clash. */
function munge(prefix: string, name: string, used: Set<string>): string {
  const base = `${prefix}_${name.replace(/[^A-Za-z0-9_]/gu, "_").toUpperCase()}`;
  let ident = base;
  let n = 2;
  while (used.has(ident)) {
    ident = `${base}_${n}`;
    n += 1;
  }
  used.add(ident);
  return ident;
}

export function collectSymbols(bank: Bank): Symbol[] {
  const used = new Set<string>();
  const out: Symbol[] = [];

  for (const program of bank.programs) {
    if (program.kind === "hook") continue;
    const name = bank.names[program.name] ?? "";
    out.push({ ident: munge("PROGRAM", name, used), name, hash: fnv1a64(name) });
  }
  for (const signal of bank.signals) {
    out.push({ ident: munge("SIGNAL", signal.name, used), name: signal.name, hash: fnv1a64(signal.name) });
  }
  for (const verb of bank.verbs) {
    out.push({ ident: munge("VERB", verb.name, used), name: verb.name, hash: fnv1a64(verb.name) });
  }
  for (const entity of bank.entities.tables) {
    const name = bank.names[entity.id] ?? "";
    out.push({ ident: munge("ENTITY", name, used), name, hash: fnv1a64(name) });
  }
  return out;
}

export function gdscriptHeader(bank: Bank): string {
  const lines = [
    "# Generated by `loom-bank build` — do not edit.",
    "#",
    "# GDScript integers are *signed* 64-bit and a literal >= 2^63 is a",
    "# parse error, so ids are emitted as signed decimals with the",
    "# unsigned hex alongside. Never print these as unsigned.",
    "class_name LoomIDs",
    "",
  ];
  for (const s of collectSymbols(bank)) {
    lines.push(`const ${s.ident} := ${asSignedDecimal(s.hash)}  # 0x${s.hash.toString(16).padStart(16, "0")} ${s.name}`);
  }
  return lines.join("\n") + "\n";
}

export function csharpHeader(bank: Bank): string {
  const lines = [
    "// Generated by `loom-bank build` — do not edit.",
    "namespace Loom {",
    "    public static class LoomIDs {",
  ];
  for (const s of collectSymbols(bank)) {
    const pascal = s.ident
      .toLowerCase()
      .split("_")
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join("");
    lines.push(`        public const ulong ${pascal} = 0x${s.hash.toString(16).padStart(16, "0")}UL; // ${s.name}`);
  }
  lines.push("    }", "}");
  return lines.join("\n") + "\n";
}

export function cppHeader(bank: Bank): string {
  const lines = [
    "// Generated by `loom-bank build` — do not edit.",
    "#pragma once",
    "#include <cstdint>",
    "",
    "namespace loom::ids {",
  ];
  for (const s of collectSymbols(bank)) {
    const ident = `k${s.ident
      .toLowerCase()
      .split("_")
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join("")}`;
    lines.push(`constexpr uint64_t ${ident} = 0x${s.hash.toString(16).padStart(16, "0")}ULL; // ${s.name}`);
  }
  lines.push("}  // namespace loom::ids");
  return lines.join("\n") + "\n";
}
